# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: issue26.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='issue26.proto',
  package='bikes',
  syntax='proto3',
  serialized_pb=_b('\n\rissue26.proto\x12\x05\x62ikes\"\x1e\n\x06\x45ngine\x12\x14\n\x0c\x64isplacement\x18\x02 \x01(\x05\"H\n\nMotorcycle\x12\r\n\x05\x62rand\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x06\x65ngine\x18\x03 \x01(\x0b\x32\r.bikes.Engineb\x06proto3')
)




_ENGINE = _descriptor.Descriptor(
  name='Engine',
  full_name='bikes.Engine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='displacement', full_name='bikes.Engine.displacement', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=54,
)


_MOTORCYCLE = _descriptor.Descriptor(
  name='Motorcycle',
  full_name='bikes.Motorcycle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='brand', full_name='bikes.Motorcycle.brand', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bikes.Motorcycle.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='engine', full_name='bikes.Motorcycle.engine', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=128,
)

_MOTORCYCLE.fields_by_name['engine'].message_type = _ENGINE
DESCRIPTOR.message_types_by_name['Engine'] = _ENGINE
DESCRIPTOR.message_types_by_name['Motorcycle'] = _MOTORCYCLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Engine = _reflection.GeneratedProtocolMessageType('Engine', (_message.Message,), dict(
  DESCRIPTOR = _ENGINE,
  __module__ = 'issue26_pb2'
  # @@protoc_insertion_point(class_scope:bikes.Engine)
  ))
_sym_db.RegisterMessage(Engine)

Motorcycle = _reflection.GeneratedProtocolMessageType('Motorcycle', (_message.Message,), dict(
  DESCRIPTOR = _MOTORCYCLE,
  __module__ = 'issue26_pb2'
  # @@protoc_insertion_point(class_scope:bikes.Motorcycle)
  ))
_sym_db.RegisterMessage(Motorcycle)


# @@protoc_insertion_point(module_scope)
